---
dist: trusty
sudo: required
language: ruby
rvm: 2.6.1
services: 
  - docker
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
before_install: 
  - gem update --system
  - gem install bundler -v 2.0.1
  - docker-compose up &
  - sleep 120 # Allowing docker-compose to get ready
  - google-chrome --headless --remote-debugging-port=9222
