---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.1
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
before_install: 
  - gem update --system
  - gem install bundler -v 2.0.1
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - wget https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
  - java -jar selenium-server-standalone-3.141.59.jar &
