---
sudo: required
language: ruby
cache: bundler
rvm:
  - 2.6.1
services: 
  - docker
  - docker-compose
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
before_install: 
  - gem update --system
  - gem install bundler -v 2.0.1
  - google-chrome-stable --headless &
  - docker-compose up &
  - sleep 60
  - ls
