---
sudo: required
language: ruby
os: linux
rvm: 2.6.1
services: 
  - docker
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
before_install: 
  - gem update --system
  - gem install bundler -v 2.0.1
  - ruby --version
  #- docker-compose up &
  #- sleep 120
