---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.1
env:
  - MOZ_HEADLESS=1
addons:
  chrome: stable
  firefox: latest
before_install: 
  - gem update --system
  - gem install bundler -v 2.0.1

