version: "3.7"
services:
  app:
    build: .
    tty: true
    depends_on:
      - hub
    volumes:
      - .:/blkbx
  hub:
    image: selenium/hub:3.141.59-vanadium
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-vanadium
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.141.59-vanadium
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub