version: "3.7"
services:
  automation:
    build: .
    tty: true
    depends_on:
      - selenium.hub
    volumes:
      - .:/blkbx
    image: blkbx/automation:0.2.0
  selenium.hub:
    image: selenium/hub:3.141.59-vanadium
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.141.59-vanadium
    depends_on:
      - selenium.hub
    environment:
      - HUB_HOST=selenium.hub
  firefox:
    image: selenium/node-firefox:3.141.59-vanadium
    depends_on:
      - selenium.hub
    environment:
      - HUB_HOST=selenium.hub